---
services:
  api:
    container_name: ${PROJECT_ID}.api
    image: ${IMAGE_PREFIX}-api
    build:
      context: ./api
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped
    env_file:
      - .env
      - .env.local
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp

  pwa:
    container_name: ${PROJECT_ID}.pwa
    image: ${IMAGE_PREFIX}-pwa
    build:
      context: ./pwa
        - .env
        - .env.local

volumes:
  caddy_config:
  caddy_data:
