---
services:
  api:
    build:
      target: frankenphp_dev
    environment:
      MERCURE_EXTRA_DIRECTIVES: demo
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-off}"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./api:/app
      - /app/var
      - ./api/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./api/frankenphp/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - /app/vendor

  pwa:
    build:
      target: dev
    environment:
      API_PLATFORM_CREATE_CLIENT_ENTRYPOINT: http://api
      API_PLATFORM_CREATE_CLIENT_OUTPUT: .
      # On Linux, you may want to comment the following line for improved performance
      WATCHPACK_POLLING: "true"
      # Development usage only
      NODE_TLS_REJECT_UNAUTHORIZED: "0"
    volumes:
      - ./pwa:/srv/app
