---
version: "3"

tasks:
  default: task -l  

  boot:prod:
    desc: boot docker container
    cmds:
      - docker compose -f compose.yaml -f compose.prod.yaml up -d

  up:
    desc: boot docker container
    cmds:
      - docker compose up -d {{.CLI_ARGS}}

  start:
    desc: start docker container
    cmds:
      - docker compose up -d {{.CLI_ARGS}}

  stop:
    desc: stop docker container
    cmds:
      - docker compose stop {{.CLI_ARGS}}

  restart:
    desc: restart docker container
    cmd: docker compose restart {{.CLI_ARGS}}
  
  rm:
    desc: cleanup containers
    cmds:
      - docker compose rm {{.CLI_ARGS}}

  build:
    desc: build dev container
    cmds:
      - task: build:php
      - task: build:pwa

  build:pwa:
    desc: Build pwa container image
    cmds:
      - docker compose build pwa {{.CLI_ARGS}}
      
  build:php:
    desc: Build php container image
    cmds:
      - docker compose build api {{.CLI_ARGS}}

  build:prod:
    desc: Build production images
    cmds:
      - docker compose -f compose.yaml -f compose.prod.yaml build

  logs:api:
    desc: show api container log
    cmds:
      - docker compose logs -f api --tail 10

  logs:pwa:
    desc: show pwa container log
    cmds:
      - docker compose logs -f pwa --tail 10

  api:shell:
    desc: execute bash shell in api container
    cmds:
      - docker compose exec api bash
  
  sf:
    desc: execute bin/console command in api container
    cmds:
      - docker compose exec api bin/console {{.CLI_ARGS}}
  
  sf:cc:
    desc: clear symfony cache
    cmds:
      - docker compose exec api bin/console cache:clear {{.CLI_ARGS}}

  composer:
    desc: execute composer in api container
    cmds:
      - docker compose exec api composer {{.CLI_ARGS}}

  pnpm:
    desc: execute pnpm in pwa container
    cmds: 
      - docker compose exec pwa pnpm {{.CLI_ARGS}}

  secrets:
    desc: generate random secrets
    cmds:
      - openssl rand -base64 -hex 32
