api_platform:
  title: Reboot API Specification
  version: 1.0.0
  mercure:
    include_type: true
  formats:
    jsonld: ['application/ld+json']
  docs_formats:
    jsonld: ['application/ld+json']
    jsonopenapi: ['application/vnd.openapi+json']
    html: ['text/html']
  defaults:
    stateless: true
    cache_headers:
      vary: ['Content-Type', 'Authorization', 'Origin']
    extra_properties:
      standard_put: true
      rfc_7807_compliant_errors: true
  event_listeners_backward_compatibility_layer: false
  keep_legacy_inflector: false

when@dev:
  api_platform:
    oauth:
      enabled: true
      pkce: true
      type: oauth2
      flow: authorizationCode
      tokenUrl: '%env(resolve:OIDC_SWAGGER_TOKEN_URL)%'
      authorizationUrl: '%env(resolve:OIDC_SWAGGER_AUTHORIZE_URL)%'
      clientId: '%env(resolve:OIDC_SWAGGER_CLIENT_ID)%'
      clientSecret: '%env(resolve:OIDC_SWAGGER_CLIENT_SECRET)%'
      scopes:
        openid: (required) Indicates that the application intends to use OIDC to verify the user's identity
        profile: (required) Get user profile
        email: (required) Get user email info
    
