# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
  secret: '%env(APP_SECRET)%'
  #csrf_protection: true
  annotations: false
  http_method_override: false
  handle_all_throwables: true

  trusted_proxies: '%env(TRUSTED_PROXIES)%'
  trusted_hosts: '%env(TRUSTED_HOSTS)%'
  # See https://caddyserver.com/docs/caddyfile/directives/reverse_proxy#headers
  trusted_headers: [ 'x-forwarded-for', 'x-forwarded-proto' ]
  php_errors:
    log: true
      
when@test:
  framework:
    test: true
