---
name: CI

on:
  workflow_dispatch:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    tags: ['v*']

jobs:
  api:
    name: API Test
    uses: kilip/reboot/.github/workflows/api.yaml@main
    secrets: inherit
  
  build-images:
    name: Build
    uses: kilip/reboot/.github/workflows/build-images.yaml@main
    needs: ["api"]
    if: ${{ needs.api.result != 'failure' && github.event_name != 'pull_request' }}

  release:
    name: Release
    needs: ["build-images"]
    if: ${{ needs.build-images.result != 'failure' && github.event_name != 'pull_request' && github.ref_name != 'main'}}
    uses: kilip/reboot/.github/workflows/release.yaml@main

